server:
  port: 2000
spring:
  application:
    name: atguigu-crowd-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mydb
    url: jdbc:mysql://localhost:3306/project_crowd?serverTimeZone=UTC
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml