person:
  userName: hsn
  boss: true
  birth: 2000/12/27
  age: 20
  car:
    name: BMW
    price: 50
    interests: [游戏,ow]
  animal:
    - 阿毛
    - 阿狗
  score: {english:50,math:90}
  salarys: [99999.9]
  allCars:
    sick:
      - {name: 小白,price: 20}
      - name: cao
        price: 20
spring:
  mvc:
    static-path-pattern: /res/**